# Generated by Django 5.0.6 on 2024-05-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_internship_skillinternship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='link',
        ),
    ]
