# Generated by Django 5.0.6 on 2024-05-26 16:03

from django.db import migrations, models
from django.utils import timezone

def data_migrate(apps, schema_editor):
    Internship = apps.get_model('authentication', 'Internship')  # Замени your_app на имя приложения
    for row in Internship.objects.all():
        row.created_at = timezone.now()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_internship_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(data_migrate),
    ]
