# Generated by Django 5.0.6 on 2024-05-26 16:14

from django.db import migrations, models
from django.utils import timezone

def data_migrate(apps, schema_editor):
    Internship = apps.get_model('authentication', 'Internship')
    for row in Internship.objects.all():
        if not row.created_at:  # Заполняем только если значение пустое
            row.created_at = timezone.now()
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_internship_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(data_migrate),  # Добавляем RunPython
    ]
