# Generated by Django 5.0.6 on 2024-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usertestresult_usertestquestionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestquestionresult',
            name='user_answer_choice',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
