# Generated by Django 5.0.6 on 2024-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_usertestquestionresult_user_answer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestquestionresult',
            name='user_answer_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/results/'),
        ),
    ]
