# Generated by Django 5.0.6 on 2024-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_usertestquestionresult_user_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='status',
            field=models.TextField(default='В обработке'),
        ),
    ]
